M: 10
N: 2
alpha: 200
augment: true
bn_size: 4
cardinality: 8
changing_lr:
- 80
- 120
checkpoint: checkpoint
commit: not_set
compression_rate: 0.5
cos_lr: true
dataset: emotiondataset
droprate: 0.3
en_wandb: true
exp_id: 00014_network==110
growth_rate: 12
initial_learning_rate: 0.1
layers: 110
model: resnet
name: first_test_network==110
'no': '0'
print_freq: 10
randaugment: true
resume: false
warm_up: false
